import { describe, it, expect, vi, beforeEach } from 'vitest';

const mockGenerateContent = vi.fn();
const mockGetGenerativeModel = vi.fn(() => ({
    generateContent: mockGenerateContent,
}));

const mockChatCompletions = vi.fn();
const mockOpenAI = vi.fn(() => ({
    chat: {
        completions: {
            create: mockChatCompletions,
        },
    },
}));

vi.mock('@google/generative-ai', () => ({
    GoogleGenerativeAI: vi.fn(() => ({
        getGenerativeModel: mockGetGenerativeModel,
    })),
}));

vi.mock('openai', () => ({
    default: mockOpenAI,
}));

const { generateDescription, generateBatchDescriptions } = await import('./ai-service');

const createMockFile = (name: string): File => {
    const blob = new Blob(['test'], { type: 'image/png' });
    return new File([blob], name, { type: 'image/png' });
};

describe('ai-service', () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });

    describe('generateDescription', () => {
        it('generates description using Gemini', async () => {
            const mockResponse = {
                alt: 'A test image',
                description: 'This is a test image for accessibility',
            };

            mockGenerateContent.mockResolvedValue({
                response: {
                    text: () => JSON.stringify(mockResponse),
                },
            });

            const file = createMockFile('test.png');
            const result = await generateDescription(
                file,
                'gemini',
                'test-key',
                'gemini-2.5-flash',
                'pt-BR',
                'concise',
                []
            );

            expect(result).toEqual(mockResponse);
            expect(mockGetGenerativeModel).toHaveBeenCalledWith({ model: 'gemini-2.5-flash' });
        });

        it('generates description using OpenAI', async () => {
            const mockResponse = {
                alt: 'A test image',
                description: 'This is a test image for accessibility',
            };

            mockChatCompletions.mockResolvedValue({
                choices: [
                    {
                        message: {
                            content: JSON.stringify(mockResponse),
                        },
                    },
                ],
            });

            const file = createMockFile('test.png');
            const result = await generateDescription(file, 'openai', 'test-key', 'gpt-4o', 'pt-BR', 'concise', []);

            expect(result).toEqual(mockResponse);
        });

        it('generates description using GitHub Models endpoint', async () => {
            const mockResponse = {
                alt: 'A test image',
                description: 'Generated by GitHub Models',
                metadata: { objects: [], people: false, decorative: false, dominant_colors: [], confidence: 0.9 },
            };

            mockChatCompletions.mockResolvedValue({
                choices: [
                    {
                        message: {
                            content: JSON.stringify(mockResponse),
                        },
                    },
                ],
            });

            const file = createMockFile('test.png');
            const result = await generateDescription(
                file,
                'github-models',
                'gh-token',
                'openai/gpt-4o',
                'pt-BR',
                'concise',
                []
            );

            expect(result).toEqual(mockResponse);
            expect(mockChatCompletions).toHaveBeenCalled();
            expect(mockOpenAI).toHaveBeenCalledWith(
                expect.objectContaining({
                    apiKey: 'gh-token',
                    baseURL: 'https://models.github.ai/inference',
                    dangerouslyAllowBrowser: true,
                })
            );
        });

        it('throws error when API fails', async () => {
            mockGenerateContent.mockRejectedValue(new Error('API Error'));

            const file = createMockFile('test.png');
            await expect(
                generateDescription(file, 'gemini', 'test-key', 'gemini-2.5-flash', 'pt-BR', 'concise', [])
            ).rejects.toThrow();
        });

        it('applies language, style and glossary in Gemini prompt', async () => {
            const mockResponse = {
                alt: 'A formal alt text',
                description: 'A formal description',
                metadata: { objects: [], people: false, decorative: false, dominant_colors: [], confidence: 0.9 },
            };

            mockGenerateContent.mockResolvedValue({
                response: {
                    text: () => JSON.stringify(mockResponse),
                },
            });

            const file = createMockFile('test.png');
            await generateDescription(
                file,
                'gemini',
                'test-key',
                'gemini-2.5-flash',
                'en-US',
                'formal',
                [{ term: 'CEO', definition: 'Chief Executive Officer' }]
            );

            const prompt = mockGenerateContent.mock.calls[0][0][0] as string;
            expect(prompt).toContain('English (US)');
            expect(prompt).toContain('Professional tone');
            expect(prompt).toContain('"CEO": Chief Executive Officer');
        });

        it('applies language and style in OpenAI prompt', async () => {
            const mockResponse = {
                alt: 'Texto',
                description: 'Descrição',
                metadata: { objects: [], people: false, decorative: false, dominant_colors: [], confidence: 0.8 },
            };

            mockChatCompletions.mockResolvedValue({
                choices: [
                    {
                        message: {
                            content: JSON.stringify(mockResponse),
                        },
                    },
                ],
            });

            const file = createMockFile('test.png');
            await generateDescription(file, 'openai', 'test-key', 'gpt-4o', 'es-ES', 'detailed', []);

            const requestPayload = mockChatCompletions.mock.calls[0][0];
            const prompt = requestPayload.messages[0].content[0].text as string;

            expect(prompt).toContain('Spanish');
            expect(prompt).toContain('Comprehensive, descriptive');
            expect(prompt).toContain('Write ALL textual fields strictly in Spanish');
        });
    });

    describe('generateBatchDescriptions', () => {
        it('processes multiple images and reports progress', async () => {
            const mockResponse = {
                alt: 'Test',
                description: 'Test description',
            };

            mockGenerateContent.mockResolvedValue({
                response: {
                    text: () => JSON.stringify(mockResponse),
                },
            });

            const files = [
                createMockFile('test1.png'),
                createMockFile('test2.png'),
            ];

            const progressCallback = vi.fn();
            const results = await generateBatchDescriptions(
                files,
                'gemini',
                'test-key',
                'gemini-2.5-flash',
                'pt-BR',
                'concise',
                [],
                progressCallback
            );

            expect(results).toHaveLength(2);
            expect(results[0].filename).toBe('test1.png');
            expect(results[1].filename).toBe('test2.png');
            expect(progressCallback).toHaveBeenCalledWith(1, 2);
            expect(progressCallback).toHaveBeenCalledWith(2, 2);
        });
    });
});
